// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStartupArgs() {
  return window['go']['main']['App']['GetStartupArgs']();
}

export function HTTPPort() {
  return window['go']['main']['App']['HTTPPort']();
}

export function IsWindowMaximized() {
  return window['go']['main']['App']['IsWindowMaximized']();
}

export function LearnWord(arg1, arg2, arg3) {
  return window['go']['main']['App']['LearnWord'](arg1, arg2, arg3);
}

export function LogError(arg1) {
  return window['go']['main']['App']['LogError'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function SaveFileDialog(arg1, arg2) {
  return window['go']['main']['App']['SaveFileDialog'](arg1, arg2);
}

export function SpellCheck(arg1, arg2) {
  return window['go']['main']['App']['SpellCheck'](arg1, arg2);
}

export function Suggest(arg1, arg2, arg3) {
  return window['go']['main']['App']['Suggest'](arg1, arg2, arg3);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMaximize() {
  return window['go']['main']['App']['WindowMaximize']();
}

export function WindowMinimize() {
  return window['go']['main']['App']['WindowMinimize']();
}

export function WindowStartDrag() {
  return window['go']['main']['App']['WindowStartDrag']();
}

export function WriteDocument(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteDocument'](arg1, arg2, arg3);
}
