// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dict} from '../models';
import {core} from '../models';

export function GetClipboardHtml():Promise<string>;

export function GetStartupArgs():Promise<Array<string>>;

export function HTTPPort():Promise<number>;

export function IsWindowMaximized():Promise<boolean>;

export function LearnWord(arg1:string,arg2:string,arg3:string):Promise<void>;

export function LogError(arg1:string):Promise<void>;

export function NewWindow():Promise<void>;

export function OpenFile(arg1:string):Promise<Record<string, any>>;

export function OpenFileDialog():Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadXLSX(arg1:string):Promise<string>;

export function SaveFileDialog(arg1:string,arg2:string):Promise<string>;

export function SetClipboardHtml(arg1:string,arg2:string):Promise<void>;

export function SpellCheck(arg1:string,arg2:string):Promise<Array<dict.SpellError>>;

export function Suggest(arg1:string,arg2:string,arg3:number):Promise<Array<dict.Candidate>>;

export function WindowClose():Promise<void>;

export function WindowMaximize():Promise<void>;

export function WindowMinimize():Promise<void>;

export function WindowStartDrag():Promise<void>;

export function WriteDocument(arg1:string,arg2:string,arg3:core.Document):Promise<void>;

export function WritePPTX(arg1:string,arg2:string):Promise<void>;

export function WriteTextFile(arg1:string,arg2:string):Promise<void>;

export function WriteXLSX(arg1:string,arg2:string):Promise<void>;
